services:
  auth_composer:
    image: composer:2.6
    container_name: auth_laravel_composer
    working_dir: /var/www
    volumes:
      - ./adaa-auth-api:/var/www
    # command: ["composer", "create-project", "--prefer-dist", "laravel/laravel", "."]
    # command: sh -c "docker-php-ext-install sockets && composer update"
    command: composer update --ignore-platform-req=ext-sockets

  auth_app:
    image: php:8.2-fpm
    container_name: auth_laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./adaa-auth-api:/var/www
    networks:
      - auth_laravel_network
      - adaa_shared_network
    # entrypoint: ["/bin/sh", "-c", "docker-php-ext-install pdo pdo_mysql && php-fpm"]
    entrypoint: ["/bin/sh", "-c", "docker-php-ext-install pdo pdo_mysql sockets && php-fpm"]

  auth_webserver:
    image: nginx:alpine
    container_name: auth_laravel_webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./adaa-auth-api:/var/www
      - ./adaa-auth-api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auth_laravel_network
    depends_on:
      - auth_app

networks:
  auth_laravel_network:
    driver: bridge
  adaa_shared_network:
    external: true