services:
  composer:
    image: composer:2.6
    container_name: backoffice_laravel_composer
    working_dir: /var/www
    volumes:
      - ./admin.adaa-learning-api:/var/www
    # command: ["composer", "create-project", "--prefer-dist", "laravel/laravel", "."]
    # command: sh -c "docker-php-ext-install sockets && composer update"
    command: composer update --ignore-platform-req=ext-sockets

  app:
    image: php:8.2-fpm
    container_name: backoffice_laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./admin.adaa-learning-api:/var/www
    networks:
      - backoffice_laravel_network
    depends_on:
      - db
    # entrypoint: ["/bin/sh", "-c", "docker-php-ext-install pdo pdo_mysql && php-fpm"]
    entrypoint: ["/bin/sh", "-c", "docker-php-ext-install pdo pdo_mysql sockets && php-fpm"]

  webserver:
    image: nginx:alpine
    container_name: backoffice_laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./admin.adaa-learning-api:/var/www
      - ./admin.adaa-learning-api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backoffice_laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: backoffice_laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"  # Added this line to expose MySQL port
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backoffice_laravel_network
      - adaa_shared_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: backoffice_laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 64M      # Add this line
      PMA_UPLOAD_LIMIT: 64M  # Add this line
      PHP_MAX_INPUT_VARS: 2000
      PHP_MEMORY_LIMIT: 512M
    networks:
      - backoffice_laravel_network
      - adaa_shared_network
    depends_on:
      - db


volumes:
  dbdata:

networks:
  backoffice_laravel_network:
    driver: bridge
  adaa_shared_network:
    external: true